language: generic 

sudo: required  # we need super user permission to execute the code.

services:
  - docker # by specifying this travis-ci unserstands that we need docker cli pre-installed.



before_install: # this contains a series of commands that gets executed before our tests are ran.
  - docker build -t sriharsha786/docker-react -f Dockerfile.dev .
 
script:       # anytime we run our test-suite on travis-Ci it assumes that our test suite runs and then exits automatically. but default "npm run test" command never exits util we press the q.it just 
  - docker run -e CI=true sriharsha786/docker-react npm run test    # hangs there util we hit the q. 


deploy:
  provider: elasticbeanstalk  # on which we are deploying  hosting provider
  app: docker-react         #application name
  env:  Dockerreact-env-1     # environment name actually app running inside the docker-react using it's  called as env 
  region: ap-south-1
  bucket_name: elasticbeanstalk-ap-south-1-534915205250
  bucket_path: docker-react
  on:
    branch: master    # we are deploying whenever it code in master branch is changing.
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY




    
 
